import { createFileRoute } from "@tanstack/react-router";
import { BriefcaseBusiness, Calendar, ChevronRight, MapPin, MoreHorizontal, Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { AppShell, PageHeader } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { applications, type Application, type ApplicationStatus } from "@/lib/mock-data";

export const Route = createFileRoute("/applications")({ head: () => ({ meta: [
  { title: "Application Tracker — JobMatch AI" }, { name: "description", content: "Track job applications, interview steps, match scores, and outcomes." },
  { property: "og:title", content: "Application Tracker — JobMatch AI" }, { property: "og:description", content: "Track job applications, interview steps, match scores, and outcomes." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Applications });

const statuses: ("All" | ApplicationStatus)[] = ["All", "Interested", "Applied", "Interview", "Offer", "Rejected"];
function Status({ value }: { value: ApplicationStatus }) { const cls = value === "Offer" || value === "Interview" ? "bg-status-found-bg text-status-found" : value === "Rejected" ? "bg-status-missing-bg text-status-missing" : value === "Interested" ? "bg-secondary text-secondary-foreground" : "bg-info-bg text-info"; return <span className={`rounded-md px-2.5 py-1 text-xs font-semibold ${cls}`}>{value}</span>; }

function Applications() {
 const [query, setQuery] = useState(""); const [status, setStatus] = useState<(typeof statuses)[number]>("All"); const [selected, setSelected] = useState<Application | null>(null);
 const filtered = useMemo(() => applications.filter((a) => (status === "All" || a.status === status) && `${a.company} ${a.position}`.toLowerCase().includes(query.toLowerCase())), [query, status]);
 return <AppShell><div className="mx-auto max-w-[1500px] px-4 py-8 sm:px-7 lg:px-10 lg:py-10"><PageHeader title="Application tracker" description="Keep every opportunity, next step, and outcome in one place." action={<Dialog><DialogTrigger asChild><Button size="lg"><Plus />Add Application</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add an application</DialogTitle><DialogDescription>Create a new mock tracker entry.</DialogDescription></DialogHeader><div className="grid gap-4 py-2"><label className="space-y-2 text-sm font-medium">Company<Input placeholder="Company name" /></label><label className="space-y-2 text-sm font-medium">Position<Input placeholder="Job title" /></label><label className="space-y-2 text-sm font-medium">Job listing URL<Input placeholder="https://" /></label><Button className="mt-2">Add to tracker</Button></div></DialogContent></Dialog>} />
 <div className="mb-5 flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="relative w-full xl:max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search company or position" className="pl-9" /></div><div className="flex gap-2 overflow-x-auto pb-1">{statuses.map((item) => <Button key={item} variant={status === item ? "default" : "outline"} size="sm" onClick={() => setStatus(item)}>{item}{item !== "All" && <span className="opacity-70">{applications.filter((a) => a.status === item).length}</span>}</Button>)}</div></div>
 <section className="surface overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-muted/60 text-xs uppercase text-muted-foreground"><tr>{["Company", "Position", "Match Score", "Status", "Applied Date", "Last Updated", "Actions"].map((h) => <th key={h} className="px-5 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{filtered.map((app) => <tr key={app.id} onClick={() => setSelected(app)} className="cursor-pointer transition-colors hover:bg-accent/35"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-md bg-avatar text-xs font-semibold text-primary">{app.initials}</span><span className="font-semibold">{app.company}</span></div></td><td className="px-5 py-4"><p className="font-medium">{app.position}</p><p className="mt-1 text-xs text-muted-foreground">{app.location}</p></td><td className="px-5 py-4"><div className="flex items-center gap-2"><div className="h-1.5 w-14 rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{ width: `${app.match}%` }} /></div><span className="font-semibold">{app.match}%</span></div></td><td className="px-5 py-4"><Status value={app.status} /></td><td className="px-5 py-4 text-muted-foreground">{app.applied}</td><td className="px-5 py-4 text-muted-foreground">{app.updated}</td><td className="px-5 py-4"><Button variant="ghost" size="icon" aria-label={`Open ${app.position}`}><MoreHorizontal /></Button></td></tr>)}</tbody></table></div>{filtered.length === 0 && <div className="py-16 text-center"><Search className="mx-auto size-7 text-muted-foreground" /><p className="mt-3 text-sm font-medium">No applications found</p><p className="mt-1 text-xs text-muted-foreground">Try a different search or filter.</p></div>}</section>
 <p className="mt-4 text-xs text-muted-foreground">Showing {filtered.length} of {applications.length} applications</p>
 <Sheet open={selected !== null} onOpenChange={(open) => !open && setSelected(null)}><SheetContent className="w-full overflow-y-auto p-0 sm:max-w-lg">{selected && <><SheetHeader className="border-b border-border p-6"><div className="mb-3 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-lg bg-avatar text-sm font-semibold text-primary">{selected.initials}</span><div><SheetTitle>{selected.position}</SheetTitle><SheetDescription>{selected.company}</SheetDescription></div></div><div className="flex flex-wrap items-center gap-2"><Status value={selected.status} /><span className="text-xs text-muted-foreground">Updated {selected.updated}</span></div></SheetHeader><div className="space-y-6 p-6"><div className="flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="size-4" />{selected.location}</div><div className="rounded-lg bg-accent p-5"><p className="text-xs font-semibold uppercase text-muted-foreground">Match score</p><div className="mt-2 flex items-end justify-between"><span className="text-3xl font-semibold">{selected.match}%</span><span className="text-xs font-medium text-primary">Strong alignment</span></div><div className="mt-4 h-2 rounded-full bg-card"><div className="h-full rounded-full bg-primary" style={{ width: `${selected.match}%` }} /></div></div><div><p className="text-xs font-semibold uppercase text-muted-foreground">Next step</p><div className="mt-2 flex items-center gap-2 rounded-lg border border-border p-4 text-sm font-medium"><Calendar className="size-4 text-primary" />{selected.nextStep}</div></div><div><p className="text-xs font-semibold uppercase text-muted-foreground">Notes</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{selected.notes}</p></div><div className="grid grid-cols-2 gap-3"><Button variant="outline">Edit details</Button><Button>Update status <ChevronRight /></Button></div></div></>}</SheetContent></Sheet>
 </div></AppShell>;
}
