/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisResultsRouteImport } from './routes/analysis-results'
import { Route as CoverLettersRouteImport } from './routes/cover-letters'
import { Route as NewAnalysisRouteImport } from './routes/new-analysis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisResultsRoute = AnalysisResultsRouteImport.update({
  id: '/analysis-results',
  path: '/analysis-results',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLettersRoute = CoverLettersRouteImport.update({
  id: '/cover-letters',
  path: '/cover-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const NewAnalysisRoute = NewAnalysisRouteImport.update({
  id: '/new-analysis',
  path: '/new-analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis-results': typeof AnalysisResultsRoute
  '/cover-letters': typeof CoverLettersRoute
  '/new-analysis': typeof NewAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis-results': typeof AnalysisResultsRoute
  '/cover-letters': typeof CoverLettersRoute
  '/new-analysis': typeof NewAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis-results': typeof AnalysisResultsRoute
  '/cover-letters': typeof CoverLettersRoute
  '/new-analysis': typeof NewAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analysis-results' | '/cover-letters' | '/new-analysis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analysis-results' | '/cover-letters' | '/new-analysis'
  id:
    '__root__' | '/' | '/analysis-results' | '/cover-letters' | '/new-analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisResultsRoute: typeof AnalysisResultsRoute
  CoverLettersRoute: typeof CoverLettersRoute
  NewAnalysisRoute: typeof NewAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis-results': {
      id: '/analysis-results'
      path: '/analysis-results'
      fullPath: '/analysis-results'
      preLoaderRoute: typeof AnalysisResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letters': {
      id: '/cover-letters'
      path: '/cover-letters'
      fullPath: '/cover-letters'
      preLoaderRoute: typeof CoverLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-analysis': {
      id: '/new-analysis'
      path: '/new-analysis'
      fullPath: '/new-analysis'
      preLoaderRoute: typeof NewAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisResultsRoute: AnalysisResultsRoute,
  CoverLettersRoute: CoverLettersRoute,
  NewAnalysisRoute: NewAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
